language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-Xmx4g"
    - JAVA_OPTS="-Xmx4g"
jdk:
 - oraclejdk8

before_install:
 - chmod +x ./mvnw
install:
 - mvn clean
script:
 - mvn test -Denv=dev -Pdep-jacoco
after_success:
 - mvn -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID coveralls:report -Pci -Denv=dev

notifications:
  slack: maxur:bIyYFLYJ0n1toR66dIr5OSbD